### ISSUE TITLE
Change the favicon and logo

### ISSUE THREAD

**Issue by greatbuilderhq** [greatbuilderhq/greatbuilder#4]
### Checked other resources
- [x] added a very descriptive title to this issue.
- [x] searched the greatbuilder documentation with the integrated search.
- [x] used the GitHub search to find a similar question and didn't find it.

### Issue Image (if any)
![5](https://github.com/greatbuilderhq/greatbuilder/assets/156208951/21df6d96-3b68-46ec-9754-48594aae3b91)

### Issue in existing code (if any)
None

### Description
Change the favicon and logo to this the give image above
>You can download it from here also or request the admin 

### System Info
Windows 11
npm 10.2.3
node 20.10.0

### Related Component
- [ ] Deployment
- [x] Nextjs
- [ ] LLMs
- [ ] Langchain
- [ ] Rust
- [ ] Python

**Comment by n0n3br** [comment]
made a pull request. already merged. maybe this can be closed

**Comment by greatbuilderhq** [comment]
Use #6 (hastag with issue number) from now onwards

Great work!!, keep going.

**Comment by n0n3br** [comment]
I used fixes #4 um pr title. Thought this would work. What should I do ?
